-- Disposable database only. Creates a minimal production-shaped schema and RLS.
\set ON_ERROR_STOP on
CREATE ROLE authenticated;
CREATE ROLE anon;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;
GRANT USAGE ON SCHEMA auth TO authenticated, anon;
CREATE TABLE public."Categories" (
 "Id" text PRIMARY KEY, "UserId" text NOT NULL, "IsHiddenInBudget" boolean NOT NULL DEFAULT false
);
CREATE TABLE public."BudgetPlans" (
 "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "CategoryId" text NOT NULL REFERENCES public."Categories"("Id"),
 "Year" integer NOT NULL, "Month" integer NOT NULL, "Amount" real NOT NULL,
 "UserId" text NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX ON public."BudgetPlans" ("CategoryId", "Year", "Month", "UserId");
ALTER TABLE public."Categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."BudgetPlans" ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_categories ON public."Categories" TO authenticated
 USING ("UserId" = auth.uid()::text) WITH CHECK ("UserId" = auth.uid()::text);
CREATE POLICY own_budgets ON public."BudgetPlans" TO authenticated
 USING ("UserId" = auth.uid()::text) WITH CHECK ("UserId" = auth.uid()::text);
GRANT SELECT, INSERT ON public."Categories", public."BudgetPlans" TO authenticated;
\ir ../18_copy_budget_to_january.sql
\ir ../18_copy_budget_to_january.sql
INSERT INTO public."Categories" VALUES
 ('new', '00000000-0000-0000-0000-000000000001', false),
 ('saved-zero', '00000000-0000-0000-0000-000000000001', false),
 ('saved-amount', '00000000-0000-0000-0000-000000000001', false),
 ('source-zero', '00000000-0000-0000-0000-000000000001', false),
 ('hidden', '00000000-0000-0000-0000-000000000001', true),
 ('other', '00000000-0000-0000-0000-000000000002', false);
INSERT INTO public."BudgetPlans" ("CategoryId", "Year", "Month", "Amount", "UserId")
 SELECT "Id", 2026, 12, CASE WHEN "Id" = 'source-zero' THEN 0 ELSE 100 END, "UserId" FROM public."Categories";
INSERT INTO public."BudgetPlans" ("CategoryId", "Year", "Month", "Amount", "UserId") VALUES
 ('saved-zero', 2027, 1, 0, '00000000-0000-0000-0000-000000000001'),
 ('saved-amount', 2027, 1, 200, '00000000-0000-0000-0000-000000000001'),
 ('new', 2027, 2, 300, '00000000-0000-0000-0000-000000000001');
SET ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', false);
DO $$
BEGIN
 ASSERT public.copy_budget_to_january(2027) = '{"copiedCount":2,"sourceCount":4}'::jsonb, 'copy counts';
 ASSERT public.copy_budget_to_january(2027) = '{"copiedCount":0,"sourceCount":4}'::jsonb, 'idempotent retry';
 ASSERT (SELECT "Amount" FROM public."BudgetPlans" WHERE "CategoryId"='saved-zero' AND "Year"=2027)=0, 'preserve saved zero';
 ASSERT (SELECT "Amount" FROM public."BudgetPlans" WHERE "CategoryId"='saved-amount' AND "Year"=2027)=200, 'preserve saved amount';
 ASSERT (SELECT "Amount" FROM public."BudgetPlans" WHERE "CategoryId"='source-zero' AND "Year"=2027)=0, 'copy source zero';
 ASSERT (SELECT "Amount" FROM public."BudgetPlans" WHERE "CategoryId"='new' AND "Year"=2027 AND "Month"=2)=300, 'preserve other months';
 ASSERT NOT EXISTS (SELECT 1 FROM public."BudgetPlans" WHERE "CategoryId"='hidden' AND "Year"=2027), 'skip hidden';
 ASSERT (SELECT count(*) FROM public."BudgetPlans" WHERE "Year"=2026)=5, 'preserve history';
 ASSERT public.copy_budget_to_january(2029) = '{"copiedCount":0,"sourceCount":0}'::jsonb, 'empty source';
 BEGIN
  PERFORM public.copy_budget_to_january(NULL);
  RAISE EXCEPTION 'accepted invalid year';
 EXCEPTION WHEN raise_exception THEN
  IF SQLERRM <> 'Invalid destination year' THEN RAISE; END IF;
 END;
END $$;
RESET ROLE;
DO $$ BEGIN
 ASSERT NOT EXISTS (SELECT 1 FROM public."BudgetPlans" WHERE "CategoryId"='other' AND "Year"=2027), 'no cross-user writes';
 ASSERT NOT has_function_privilege('anon','public.copy_budget_to_january(integer)','EXECUTE'), 'anonymous access denied';
END $$;
SET ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000002', false);
DO $$ BEGIN
 ASSERT public.copy_budget_to_january(2027) = '{"copiedCount":1,"sourceCount":1}'::jsonb, 'second user isolated';
END $$;
SELECT set_config('request.jwt.claim.sub', '', false);
DO $$ BEGIN
 BEGIN
  PERFORM public.copy_budget_to_january(2027);
  RAISE EXCEPTION 'accepted unauthenticated call';
 EXCEPTION WHEN raise_exception THEN
  IF SQLERRM <> 'Authentication required' THEN RAISE; END IF;
 END;
END $$;
RESET ROLE;
SELECT 'All copy-to-January SQL assertions passed' AS result;
