// <auto-generated />
using System;
using FinanceFlow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceFlow.Api.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260213195251_MakeBudgetPositionIdNullable")]
    partial class MakeBudgetPositionIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("FinanceFlow.Api.Models.Domain.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Bank Account",
                            Type = "Bank"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Cash on Hand",
                            Type = "Cash"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Credit Card 1",
                            Type = "Credit Card"
                        });
                });

            modelBuilder.Entity("FinanceFlow.Api.Models.Domain.BudgetCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "c1",
                            Group = "Work Income",
                            Name = "Employment (Net)",
                            Type = "Income"
                        },
                        new
                        {
                            Id = "c2",
                            Group = "Work Income",
                            Name = "Side Hustle (Net)",
                            Type = "Income"
                        },
                        new
                        {
                            Id = "c3",
                            Group = "Capital Income",
                            Name = "Dividends (Net)",
                            Type = "Income"
                        },
                        new
                        {
                            Id = "c4",
                            Group = "Housing",
                            Name = "Rent",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c5",
                            Group = "Housing",
                            Name = "Utilities",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c6",
                            Group = "Housing",
                            Name = "Internet",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c7",
                            Group = "Groceries",
                            Name = "Groceries",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c8",
                            Group = "Fun",
                            Name = "Going Out",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c9",
                            Group = "Fun",
                            Name = "Shopping",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c10",
                            Group = "Self-Care",
                            Name = "Gym",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c11",
                            Group = "Self-Care",
                            Name = "Body Care & Medicine",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c12",
                            Group = "Transportation",
                            Name = "Car Gas",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c13",
                            Group = "Transportation",
                            Name = "Metro Ticket",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c14",
                            Group = "Entertainment",
                            Name = "Netflix",
                            Type = "Expenses"
                        },
                        new
                        {
                            Id = "c15",
                            Group = "Retirement",
                            Name = "Roth IRA",
                            Type = "Savings"
                        },
                        new
                        {
                            Id = "c16",
                            Group = "Emergency",
                            Name = "Emergency Fund",
                            Type = "Savings"
                        },
                        new
                        {
                            Id = "c17",
                            Group = "Investments",
                            Name = "Stock Portfolio",
                            Type = "Savings"
                        },
                        new
                        {
                            Id = "c18",
                            Group = "Car Debt",
                            Name = "Car Loan",
                            Type = "Debt"
                        },
                        new
                        {
                            Id = "c19",
                            Group = "Credit Card Debt",
                            Name = "Credit Card Debt",
                            Type = "Debt"
                        },
                        new
                        {
                            Id = "c20",
                            Group = "Student Loan Debt",
                            Name = "Undergraduate Loan",
                            Type = "Debt"
                        });
                });

            modelBuilder.Entity("FinanceFlow.Api.Models.Domain.BudgetPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("BudgetPlans");
                });

            modelBuilder.Entity("FinanceFlow.Api.Models.Domain.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "$",
                            StartMonth = 1,
                            StartYear = 2026
                        });
                });

            modelBuilder.Entity("FinanceFlow.Api.Models.Domain.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("BudgetPositionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BudgetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BudgetPositionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceFlow.Api.Models.Domain.BudgetPlan", b =>
                {
                    b.HasOne("FinanceFlow.Api.Models.Domain.BudgetCategory", "Category")
                        .WithMany("BudgetPlans")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceFlow.Api.Models.Domain.Transaction", b =>
                {
                    b.HasOne("FinanceFlow.Api.Models.Domain.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceFlow.Api.Models.Domain.BudgetCategory", "BudgetPosition")
                        .WithMany("Transactions")
                        .HasForeignKey("BudgetPositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("BudgetPosition");
                });

            modelBuilder.Entity("FinanceFlow.Api.Models.Domain.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceFlow.Api.Models.Domain.BudgetCategory", b =>
                {
                    b.Navigation("BudgetPlans");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
