import { test, expect } from '../../fixtures/base.fixture';

test('sorts one section, edits amounts, restores manual order and resets on year/tab changes', async ({ budgetPlanPage }) => {
  const { page } = budgetPlanPage;
  await page.clock.setFixedTime(new Date('2026-01-15T12:00:00Z'));
  await budgetPlanPage.goto();
  await budgetPlanPage.switchToEditTab();
  let reorderRequests = 0;
  page.on('request', request => { if (request.url().includes('/rpc/reorder_category')) reorderRequests++; });
  const sort = page.getByRole('button', { name: /^Expenses, Jan:/ });
  const rows = page.locator('tr[draggable]').filter({ hasText: /Rent|Groceries/ });
  const remaining = await budgetPlanPage.getRemainingRow().textContent();
  await sort.click();
  await expect(rows.first()).toContainText('Rent');
  await expect(rows.first()).toHaveAttribute('draggable', 'false');
  await sort.click();
  await expect(rows.first()).toContainText('Groceries');
  await expect(page.getByRole('button', { name: /^Income, Jan:/ })).toHaveAccessibleName(/Manual order/);
  expect(await budgetPlanPage.getRemainingRow().textContent()).toBe(remaining);
  await sort.click();
  await expect(rows.first()).toContainText('Rent');
  await expect(rows.first()).toHaveAttribute('draggable', 'true');
  await sort.click();
  const grocery = budgetPlanPage.getCellInput('Groceries', 0);
  await grocery.fill('2500');
  await expect(rows.first()).toContainText('Rent');
  await grocery.press('Enter');
  await expect(rows.first()).toContainText('Groceries');
  await expect(grocery).toHaveValue('2,500.00');
  expect(reorderRequests).toBe(0);
  await budgetPlanPage.selectYear('2027');
  await expect(sort).toHaveAccessibleName(/Manual order/);
  await sort.click();
  await budgetPlanPage.overviewTab.click();
  await budgetPlanPage.switchToEditTab();
  await expect(sort).toHaveAccessibleName(/Manual order/);
});

test('keeps sorted values when a save fails and fills the next month with focus on the same category', async ({ budgetPlanPage }) => {
  const { page } = budgetPlanPage;
  await page.clock.setFixedTime(new Date('2026-01-15T12:00:00Z'));
  await budgetPlanPage.goto();
  await budgetPlanPage.switchToEditTab();
  await page.getByRole('button', { name: /^Income, Apr:/ }).click();
  const sideMarch = budgetPlanPage.getCellInput('Side Hustle (Net)', 2);
  await sideMarch.fill('6000');
  await sideMarch.press('Shift+Tab');
  const sideApril = budgetPlanPage.getCellInput('Side Hustle (Net)', 3);
  await expect(sideApril).toBeFocused();
  await expect(sideApril).toHaveValue('6,000.00');
  const rows = page.locator('tr[draggable]').filter({ hasText: /Employment \(Net\)|Side Hustle \(Net\)/ });
  await expect(rows.first()).toContainText('Side Hustle (Net)');
  await page.route('**/rest/v1/rpc/set_budget_amount', route => route.fulfill({ status: 500, json: { message: 'Save failed' } }));
  await sideApril.fill('10');
  await sideApril.press('Enter');
  await expect(page.getByText('Failed to update budget', { exact: true })).toBeVisible();
  await expect(sideApril).toHaveValue('6,000.00');
  await expect(rows.first()).toContainText('Side Hustle (Net)');
});

test('mobile preserves section-specific direction across months, supports edits and resets across years', async ({ budgetPlanPage }) => {
  const { page } = budgetPlanPage;
  await page.clock.setFixedTime(new Date('2026-01-15T12:00:00Z'));
  await page.setViewportSize({ width: 390, height: 844 });
  await budgetPlanPage.goto();
  await budgetPlanPage.editBudgetTab.click();
  await page.getByRole('button', { name: 'Expenses', exact: true }).click();
  const sort = page.getByRole('button', { name: /^Expenses, / });
  await sort.click();
  await sort.click();
  await expect(page.getByRole('textbox').first()).toHaveValue('800.00');
  await page.getByRole('button', { name: 'Next month', exact: true }).click();
  await expect(sort).toHaveAccessibleName(/Expenses, Feb: Lowest to highest/);
  await page.getByRole('button', { name: 'Income', exact: true }).click();
  await expect(page.getByRole('button', { name: /^Income, Feb:/ })).toHaveAccessibleName(/Manual order/);
  await page.getByRole('button', { name: 'Expenses', exact: true }).click();
  await expect(sort).toHaveAccessibleName(/Lowest to highest/);
  const firstInput = page.getByRole('textbox').first();
  await firstInput.fill('2500');
  await firstInput.press('Enter');
  await expect(page.getByRole('textbox').first()).toHaveValue('1,200.00');
  await expect(page.getByRole('textbox').last()).toHaveValue('2,500.00');
  await sort.click();
  await expect(sort).toHaveAccessibleName(/Manual order/);
  await sort.click();
  await page.getByRole('button', { name: 'Previous month', exact: true }).click();
  await page.getByRole('button', { name: 'Previous month', exact: true }).click();
  await page.getByRole('button', { name: 'Expenses', exact: true }).click();
  await expect(sort).toHaveAccessibleName(/Expenses, Dec: Manual order/);
});
